version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./src:/app/src
    depends_on:
      - db
    environment:
      SQLALCHEMY_DATABASE_URI: sqlite:///your_database.db

  db:
    image: "postgres:13"  # Using PostgreSQL as an example
    environment:
      POSTGRES_DB: your_database
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
